update the pipeline

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -71,7 +71,8 @@ jobs:
             # ✅ Then: select or create workspace
             terraform workspace select $ENV || terraform workspace new $ENV
 
-            terraform fmt -check
+            terraform fmt -check || echo "⚠️ Format check failed. Please run 'terraform fmt' locally."
+
             terraform validate
 
             if [[ "${{ github.event.inputs.destroy }}" == "true" ]]; then
